#!/bin/bash
# NPM Package requires an entrypoint for the library. In our case, we need to
# export everything that was generated by ts-proto.
# This script goes through each *.ts file and adds its exports to the
# index.ts file.

# Note: The library must be compiled with tsc after index.ts was generated.
# See the build script on package.json

cd src
rm index.ts
touch index.ts

for filename in $(find ./ -name "*.ts"); do
  if [[ "$filename" == *"index.ts"* ]]; then
    continue
  fi
  echo "export * from \"${filename%.*}\";" >> index.ts
done
